name: alghwalbi_background_location
description: A location plugin that works in the background. Supports Android and iOS.
version: 0.0.2
homepage: https://github.com/ahmedabdelrahmanalghwalbi/alghwalbi_background_location
repository: https://github.com/ahmedabdelrahmanalghwalbi/alghwalbi_background_location
issue_tracker: https://github.com/ahmedabdelrahmanalghwalbi/alghwalbi_background_location/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  background_locator_3: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
